### ISSUE TITLE
باگ هنگام ارسال پیامک

### ISSUE THREAD

**Issue by d4rkr3pt0r** [hooman-mirghasemi/Laravel-iran-sms#4]
سلام. در api مگفا در فایل 

`hooman-mirghasemi\laravel-iran-sms\src\Drivers\Magfa.php`

در خط 36 هنگامی که پیامک بدون مشکل ارسال میشه و پاسخ رو دریافت میکنه، `status` برابر با `0` هست ولی چیزی return نمیشه و ادامه کد اجرا میشه و میره به خط 43 و در این قسمت ارور میده:

`$this->getErrors()[$response->status]['title']`
در واقع وقتی پیامک ارسال نشده باید به اینجا برسه تا عنوان ارور رو دریافت کنه

**Comment by hooman-mirghasemi** [comment]
بله ممکن است چون در زمان ایجاد این پکیج این پنل پیامکی رو نداشته لطفا در یک پول ریکویست تغییرات مورد نیاز رو ارسال فرمایید
